config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'home', to: 'static_pages#home'
  get 'basics', to: 'static_pages#basics'
  get 'ruby', to: 'static_pages#ruby'
  get 'git', to: 'static_pages#git'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render html: "Hola mundo"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def basics
  end

  def ruby
  end

  def git
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppOne</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/basics.html.erb
<h1> ¿Qué es un resource en el contexto de una aplicación web REST en Ruby on Rails?  </h1>
<p> Es el conjunto de rutas http, definidas para los modelos de un proyecto en ruby.
Es el conjunto de rutas http, definidas para los modelos de un proyecto en ruby. </p>

<h1> ¿Qué puede hacerse con un resource? </h1>
<p> Se pueden generar aplicaciones que permitan la creación, recolección y modificación de datos para una posible visualización o acción.</p>

<h1> ¿Qué es RESTful routing? </h1>
<p> Es el conjunto de reglas usadas para la creación de rutas en las páginas web, aplicando métodos y acciones al protocolo http. </p>

<h1> ¿Cuántas acciones básicas tiene esta filosofía? </h1>
<h1> ¿Cuáles son? </h1>
<h1> ¿Cuáles verbos HTTP se utilizan en cada una de ellas? </h1>
<p> Son 7 acciones básicas que se describen a continuación:
INDEX con el verbo GET que muestra una lista de todos los objetos.
NEW con el verbo GET que retorna un formulario para crear un nuevo objeto
CREATE con el verbo POST que crea un nuevo objeto
SHOW con el verbo GET que muestra un objeto
EDIT con el verbo GET que retorna un formulario para editar un objeto
UPDATE con el verbo PATCH que actualiza un objeto
DESTROY con el verbo DELETE que elimina un objeto
</p>

<p>
<%= link_to "home", home_path %>
</p>

app/views/static_pages/git.html.erb
<h1> Inicialización de un repositorio de git nuevo en una aplicación existente.   </h1>
<p> git init    </p>

<h1> Creación de un nuevo branch.   </h1>
<p>  Con el comando git branch seguido del nombre de la rama que queremos crear.   </p>

<h1> Realizar un commit incluyendo todos los cambios actuales.   </h1>
<p> git add . para agregar todos los cambios, y luego git commit  -m “comentario”    </p>

<h1> Cómo enviar el código al repositorio remoto.   </h1>
<p>  git push   </p>

<h1> Cómo configurar el origen del repositorio remoto para evitar escribirlo siempre cada vez que se hace un push o un pull.   </h1>
<p> git remote add nombre url    </p>

<h1>  Diferencia entre un reset y revert.  </h1>
<p>   git reset borra todos los comit que se tenían en cola para subir.
git revert, revierte a un punto o comentario anterior, sin borrar ningún otro commit  </p>

<h1> Además de cambiar de ramas, para que más se puede utilizar el comando git checkout   </h1>
<p>  para crear ramas por ejemplo git checkout -b <branch-nombre>   </p>

<h1> Como puede ver los commits que se han realizado en el proyecto.   </h1>
<p>  git log   </p>

<h1>  He modificado dos archivos y quiero hacer un commit por cada uno de ellos, ¿como lo puedo hacer?  </h1>
<p>  git add archivo.extensión  es importante tener clara la extensión del archivo a subir   </p>

<h1>    </h1>
<p>     </p>



<p>
<%= link_to "home", home_path %>
</p>

app/views/static_pages/home.html.erb
<h1>  <%= Time.now.strftime("%H:%M") %>
      <%= I18n.l(Date.today, format: '%A, %d de %B de %Y') %>
</h1>



<p>
<%= link_to "basics", basics_path %>
<%= link_to "ruby", ruby_path %>
<%= link_to "git", git_path %>
</p>

app/views/static_pages/ruby.html.erb
<h1> Interpolación de strings.  </h1>
<p>  Para este ejemplo abrimos la terminal de ruby y creamos una variable por ejemplo a = “Diego”  creamos otra variable saludo = “Hola soy # {a}”, alli observamos la interpolación de la variable a en la cadena de la variable saludo. Se debe mantener la sintaxis #[variable_a_interpolar] </p>

<h1> Como se declara un array y como se adiciona un elemento al final del array.  </h1>
<p> La sintaxis para definir un array en ruby es [elemento1, elemento2,]
este array se puede declarar en una variable y puede contener diferentes tipos de datos.
Para adicionar un elemento al final del array debe tener en cuenta el orden de los elementos los cuales inician desde el 0 = elemento1  1= elemento2, si quiero agregar el elemento3 al array alojado en la variable pueodo usar  el método push donde  su sintaxis es variable.push(elemeto3), o el operador equivalente a push que es >>  variable >> elemento3. </p>

<h1> Cómo se declara un hash.  </h1>
<p> Se declaran mediante las llaves {} y su contenido tiene una llave y un valor asociado a esta llave; {key:value} para separar los pares de llaves y valores se usa la coma ,  los hash también se pueden agregar a variables.Se declaran mediante las llaves {} y su contenido tiene una llave y un valor asociado a esta llave; {key:value} para separar los pares de llaves y valores se usa la coma ,  los hash también se pueden agregar a variables.  </p>

<h1> Cómo se itera un hash utilizando el comando each  </h1>
<p>  El siguiente ejemplo de hash;  variable = {“key” => “value”} se itera de la siguiente forma:
variable.each do |key, value|, por medio de los bloques.
ejemplo:
datos_personales = {“nombre” =>”diego”, “apellido” => “puentes”, “edad”=>26}
datos_personales.each do |llave, valor|
	puts “#{llave}: #{valor}”
end  </p>


<h1> ¿Qué es un block en ruby? De un ejemplo de cómo utilizarlo.  </h1>
<p>  Es la forma en que ruby permite unir arreglos y rangos.
Ejemplo [1,2,3,4].each do |mumero| puts 2 * numeo end 
los bloques también se pueden delimitar con las llaves {}
[1,2,3,4].each { |numero| puts 2 * numero   </p>


<h1> ¿Cuál es la convención en Ruby a la hora de nombrar variables? </h1>
<p>  nombre_de_variable = “valor”
depende el tipo de valor que contenga la variable llevará ""  </p>


<p>
<%= link_to "home", home_path %>
</p>